//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxRetailSOAPI.AxUserSeccion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogonAsUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser {
            get {
                return this.LogonAsUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonAsUserField, value) != true)) {
                    this.LogonAsUserField = value;
                    this.RaisePropertyChanged("LogonAsUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag {
            get {
                return this.PropertyBagField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyBagField, value) != true)) {
                    this.PropertyBagField = value;
                    this.RaisePropertyChanged("PropertyBag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class AifFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomDetailXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AxRetailSOAPI.AxUserSeccion.FaultMessageList[] FaultMessageListArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AxRetailSOAPI.AxUserSeccion.InfologMessage[] InfologMessageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XppExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AxRetailSOAPI.AxUserSeccion.FaultMessageList[] FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AxRetailSOAPI.AxUserSeccion.InfologMessage[] InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessageList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AxRetailSOAPI.AxUserSeccion.FaultMessage[] FaultMessageArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AxRetailSOAPI.AxUserSeccion.FaultMessage[] FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    [System.SerializableAttribute()]
    public partial class InfologMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AxRetailSOAPI.AxUserSeccion.InfologMessageType InfologMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AxRetailSOAPI.AxUserSeccion.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessControlledItemKey", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class AccessControlledItemKey : AxRetailSOAPI.AxUserSeccion.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AxRetailSOAPI.AxUserSeccion.AccessControlledType ItemTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubItemNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AxRetailSOAPI.AxUserSeccion.AccessControlledType ItemType {
            get {
                return this.ItemTypeField;
            }
            set {
                if ((this.ItemTypeField.Equals(value) != true)) {
                    this.ItemTypeField = value;
                    this.RaisePropertyChanged("ItemType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubItemName {
            get {
                return this.SubItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubItemNameField, value) != true)) {
                    this.SubItemNameField = value;
                    this.RaisePropertyChanged("SubItemName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AxRetailSOAPI.AxUserSeccion.CurrencyInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AxRetailSOAPI.AxUserSeccion.UserSessionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AxRetailSOAPI.AxUserSeccion.AccessControlledItemKey))]
    public partial class XppObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyInfo", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class CurrencyInfo : AxRetailSOAPI.AxUserSeccion.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISOCurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExchangeRate {
            get {
                return this.ExchangeRateField;
            }
            set {
                if ((this.ExchangeRateField.Equals(value) != true)) {
                    this.ExchangeRateField = value;
                    this.RaisePropertyChanged("ExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISOCurrencyCode {
            get {
                return this.ISOCurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ISOCurrencyCodeField, value) != true)) {
                    this.ISOCurrencyCodeField = value;
                    this.RaisePropertyChanged("ISOCurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix {
            get {
                return this.PrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefixField, value) != true)) {
                    this.PrefixField = value;
                    this.RaisePropertyChanged("Prefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSessionInfo", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class UserSessionInfo : AxRetailSOAPI.AxUserSeccion.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AOSLocaleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AXLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AxRetailSOAPI.AxUserSeccion.Timezone CompanyTimeZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AxRetailSOAPI.AxUserSeccion.CurrencyInfo CurrencyInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSysAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AxRetailSOAPI.AxUserSeccion.PreferredCalendar UserPreferredCalendarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AxRetailSOAPI.AxUserSeccion.Timezone UserPreferredTimeZoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AOSLocaleName {
            get {
                return this.AOSLocaleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AOSLocaleNameField, value) != true)) {
                    this.AOSLocaleNameField = value;
                    this.RaisePropertyChanged("AOSLocaleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AXLanguage {
            get {
                return this.AXLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.AXLanguageField, value) != true)) {
                    this.AXLanguageField = value;
                    this.RaisePropertyChanged("AXLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AxRetailSOAPI.AxUserSeccion.Timezone CompanyTimeZone {
            get {
                return this.CompanyTimeZoneField;
            }
            set {
                if ((this.CompanyTimeZoneField.Equals(value) != true)) {
                    this.CompanyTimeZoneField = value;
                    this.RaisePropertyChanged("CompanyTimeZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AxRetailSOAPI.AxUserSeccion.CurrencyInfo CurrencyInfo {
            get {
                return this.CurrencyInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyInfoField, value) != true)) {
                    this.CurrencyInfoField = value;
                    this.RaisePropertyChanged("CurrencyInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSysAdmin {
            get {
                return this.IsSysAdminField;
            }
            set {
                if ((this.IsSysAdminField.Equals(value) != true)) {
                    this.IsSysAdminField = value;
                    this.RaisePropertyChanged("IsSysAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AxRetailSOAPI.AxUserSeccion.PreferredCalendar UserPreferredCalendar {
            get {
                return this.UserPreferredCalendarField;
            }
            set {
                if ((this.UserPreferredCalendarField.Equals(value) != true)) {
                    this.UserPreferredCalendarField = value;
                    this.RaisePropertyChanged("UserPreferredCalendar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AxRetailSOAPI.AxUserSeccion.Timezone UserPreferredTimeZone {
            get {
                return this.UserPreferredTimeZoneField;
            }
            set {
                if ((this.UserPreferredTimeZoneField.Equals(value) != true)) {
                    this.UserPreferredTimeZoneField = value;
                    this.RaisePropertyChanged("UserPreferredTimeZone");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessControlledType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum AccessControlledType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MenuItemDisplay = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MenuItemOutput = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MenuItemAction = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebUrlItem = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebActionItem = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebManagedContentItem = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Table = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TableField = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timezone", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum Timezone : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS1200INTERNATIONALDATELINEWEST = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS1100COORDINATEDUNIVERSALTIME = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS1000HAWAII = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0900ALASKA = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0800PACIFICTIME = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0800TIJUANA_BAJACALIFORNIA = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0700ARIZONA = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0700MOUNTAINTIME = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0700CHIHUAHUA_LAPAZ_MAZATLAN = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0600CENTRALAMERICA = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0600CENTRALTIME = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0600GUADALAJARA_MEXICOCITY = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0600SASKATCHEWAN = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0500BOGOTA_LIMA_QUITO_RIOBRANCO = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0500EASTERNTIME = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0500INDIANA = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0430CARACAS = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0400ASUNCION = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0400ATLANTICTIME = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0400LAPAZ = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0400MANAUS = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0400SANTIAGO = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0330NEWFOUNDLAND = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300BRASILIA = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300BUENOSAIRES = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300BUENOSAIRES_GEORGETOWN = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300GREENLAND = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300MONTEVIDEO = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300_SALVADOR = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0200MIDATLANTIC = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0100AZORES = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0100CAPEVERDIS = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_CASABLANCA = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_COORDINATEDUNIVERSALTIME = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_CASABLANCA_MONTROVIA_REYKJAVIK = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_DUBLIN_EDINBURGH_LISBON_LONDON = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100_AMSTERDAM_BERLIN_BERN_ROME = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100BELGRADE_BRATISLAVA_BUDAPEST = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100BRUSSELS_COPENHAGEN_MADRID = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100SARAJEVO_SKOPJE_WARSAW_ZAGREB = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100TRIPOLI = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100WESTCENTRALAFRICA = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200AMMAN = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200ATHENS_BUCHAREST_ISTANBUL = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200BEIRUT = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200MINSK = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200CAIRO = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200_DAMASCUS = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200HARARE_PRETORIA = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200HELSINKI_KYIV_RIGA_VILNIUS = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200ISTANBUL = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200JERUSALEM = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200WINDHOEK = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_PLUS0300KALININGRAD_MINSK = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0300BAGHDAD = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0300KUWAIT_RIYADH = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0300MOSCOW_STPETERSBURG_VOLGOGRAD = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400PORTLOUIS = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0300NAIROBI = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0300TBILISI = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0330TEHRAN = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400ABUDHABI_MUSCAT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400BAKU = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400IZHEVSK_SAMARA = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400CAUCASUSSTANDARDTIME = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400YEREVAN = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0430KABUL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0500EKATERINBURG = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0500ISLAMABAD_KARACHI = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0500ISLAMABAD_KARACHI_TASHKENT = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0530CHENNAI_KOLKATA_MUMBAI = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0530SRIJAYAWARDENEPURA = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0545KATHMANDU = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0600ASTANA_DHAKA = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0600DHAKA = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0600ALMATY_NOVOSIBIRSK = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0630_YANGON = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0700_BANGKOK_HANOI_JAKARTA = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0700KRASNOYARSK = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800BEIJING_CHONGQING_HONGKONG = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800IRKUTSK_ULAANBATAAR = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800_ULAANBAATAR = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800KUALALUMPUR_SINGAPORE = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800PERTH = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800TAIPEI = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0900OSAKA_SAPPORO_TOKYO = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0900SEOUL = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0900YAKUTSK = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0930ADELAIDE = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0930DARWIN = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1000BRISBANE = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1000CANBERRA_MELBOURNE_SYDNEY = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1000GUAM_PORTMORESBY = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1000HOBART = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1000VLADIVOSTOK = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1100CHOKURDAKH = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1100MAGADAN_SOLOMONIS = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0600MAGADAN = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1200ANADYR_PETRO_KAMCHATSKY = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1200AUCKLAND_WELLINGTON = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1200COORDINATEDUNIVERSALTIME = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1200FIJI_KAMCHATKA_MARSHALLIS = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS1100MIDWAYISLAND_SAMOA = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1300NUKU_ALOFA = 73,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreferredCalendar", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum PreferredCalendar : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gregorian = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hijri = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UmAlQura = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessRight", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum AccessRight : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAccess = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        View = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Edit = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correction = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", ConfigurationName="AxUserSeccion.UserSessionService")]
    public interface UserSessionService {
        
        // CODEGEN: Generating message contract since the wrapper name (UserSessionServiceGetPartitionKeyRequest) of message UserSessionServiceGetPartitionKeyRequest does not match the default value (GetPartitionKey)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKey", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxUserSeccion.AifFault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeyAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyResponse GetPartitionKey(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKey", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeyResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyResponse> GetPartitionKeyAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (UserSessionServiceGetPartitionKeysForUserRequest) of message UserSessionServiceGetPartitionKeysForUserRequest does not match the default value (GetPartitionKeysForUser)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeysForUser", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeysForUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxUserSeccion.AifFault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeysForUserAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserResponse GetPartitionKeysForUser(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeysForUser", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeysForUserResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserResponse> GetPartitionKeysForUserAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (UserSessionServiceGetAccessRightsRequest) of message UserSessionServiceGetAccessRightsRequest does not match the default value (GetAccessRights)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetAcce" +
            "ssRights", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetAcce" +
            "ssRightsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxUserSeccion.AifFault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetAcce" +
            "ssRightsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsResponse GetAccessRights(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetAcce" +
            "ssRights", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetAcce" +
            "ssRightsResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsResponse> GetAccessRightsAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (UserSessionServiceGetUserSessionInfoRequest) of message UserSessionServiceGetUserSessionInfoRequest does not match the default value (GetUserSessionInfo)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetUser" +
            "SessionInfo", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetUser" +
            "SessionInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxUserSeccion.AifFault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetUser" +
            "SessionInfoAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoResponse GetUserSessionInfo(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetUser" +
            "SessionInfo", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetUser" +
            "SessionInfoResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoResponse> GetUserSessionInfoAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (UserSessionServiceIsSinglePartitionSystemRequest) of message UserSessionServiceIsSinglePartitionSystemRequest does not match the default value (IsSinglePartitionSystem)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/IsSingl" +
            "ePartitionSystem", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/IsSingl" +
            "ePartitionSystemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxUserSeccion.AifFault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/IsSingl" +
            "ePartitionSystemAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemResponse IsSinglePartitionSystem(AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/IsSingl" +
            "ePartitionSystem", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/IsSingl" +
            "ePartitionSystemResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemResponse> IsSinglePartitionSystemAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (UserSessionServiceRemoveTimeZoneRequest) of message UserSessionServiceRemoveTimeZoneRequest does not match the default value (RemoveTimeZone)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/RemoveT" +
            "imeZone", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/RemoveT" +
            "imeZoneResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxUserSeccion.AifFault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/RemoveT" +
            "imeZoneAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneResponse RemoveTimeZone(AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/RemoveT" +
            "imeZone", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/RemoveT" +
            "imeZoneResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneResponse> RemoveTimeZoneAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (UserSessionServiceApplyTimeZoneRequest) of message UserSessionServiceApplyTimeZoneRequest does not match the default value (ApplyTimeZone)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/ApplyTi" +
            "meZone", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/ApplyTi" +
            "meZoneResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxUserSeccion.AifFault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/ApplyTi" +
            "meZoneAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneResponse ApplyTimeZone(AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/ApplyTi" +
            "meZone", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/ApplyTi" +
            "meZoneResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneResponse> ApplyTimeZoneAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceGetPartitionKeyRequest", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceGetPartitionKeyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public AxRetailSOAPI.AxUserSeccion.CallContext CallContext;
        
        public UserSessionServiceGetPartitionKeyRequest() {
        }
        
        public UserSessionServiceGetPartitionKeyRequest(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceGetPartitionKeyResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceGetPartitionKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public string response;
        
        public UserSessionServiceGetPartitionKeyResponse() {
        }
        
        public UserSessionServiceGetPartitionKeyResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceGetPartitionKeysForUserRequest", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceGetPartitionKeysForUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public AxRetailSOAPI.AxUserSeccion.CallContext CallContext;
        
        public UserSessionServiceGetPartitionKeysForUserRequest() {
        }
        
        public UserSessionServiceGetPartitionKeysForUserRequest(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceGetPartitionKeysForUserResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceGetPartitionKeysForUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public string[] response;
        
        public UserSessionServiceGetPartitionKeysForUserResponse() {
        }
        
        public UserSessionServiceGetPartitionKeysForUserResponse(string[] response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceGetAccessRightsRequest", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceGetAccessRightsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public AxRetailSOAPI.AxUserSeccion.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public AxRetailSOAPI.AxUserSeccion.AccessControlledItemKey[] _keys;
        
        public UserSessionServiceGetAccessRightsRequest() {
        }
        
        public UserSessionServiceGetAccessRightsRequest(AxRetailSOAPI.AxUserSeccion.CallContext CallContext, AxRetailSOAPI.AxUserSeccion.AccessControlledItemKey[] _keys) {
            this.CallContext = CallContext;
            this._keys = _keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceGetAccessRightsResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceGetAccessRightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public AxRetailSOAPI.AxUserSeccion.AccessRight[] response;
        
        public UserSessionServiceGetAccessRightsResponse() {
        }
        
        public UserSessionServiceGetAccessRightsResponse(AxRetailSOAPI.AxUserSeccion.AccessRight[] response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceGetUserSessionInfoRequest", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceGetUserSessionInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public AxRetailSOAPI.AxUserSeccion.CallContext CallContext;
        
        public UserSessionServiceGetUserSessionInfoRequest() {
        }
        
        public UserSessionServiceGetUserSessionInfoRequest(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceGetUserSessionInfoResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceGetUserSessionInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public AxRetailSOAPI.AxUserSeccion.UserSessionInfo response;
        
        public UserSessionServiceGetUserSessionInfoResponse() {
        }
        
        public UserSessionServiceGetUserSessionInfoResponse(AxRetailSOAPI.AxUserSeccion.UserSessionInfo response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceIsSinglePartitionSystemRequest", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceIsSinglePartitionSystemRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public AxRetailSOAPI.AxUserSeccion.CallContext CallContext;
        
        public UserSessionServiceIsSinglePartitionSystemRequest() {
        }
        
        public UserSessionServiceIsSinglePartitionSystemRequest(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceIsSinglePartitionSystemResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceIsSinglePartitionSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public bool response;
        
        public UserSessionServiceIsSinglePartitionSystemResponse() {
        }
        
        public UserSessionServiceIsSinglePartitionSystemResponse(bool response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceRemoveTimeZoneRequest", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceRemoveTimeZoneRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public AxRetailSOAPI.AxUserSeccion.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public System.DateTime dateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=1)]
        public int timeZoneOffset;
        
        public UserSessionServiceRemoveTimeZoneRequest() {
        }
        
        public UserSessionServiceRemoveTimeZoneRequest(AxRetailSOAPI.AxUserSeccion.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset) {
            this.CallContext = CallContext;
            this.dateTime = dateTime;
            this.timeZoneOffset = timeZoneOffset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceRemoveTimeZoneResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceRemoveTimeZoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public System.DateTime response;
        
        public UserSessionServiceRemoveTimeZoneResponse() {
        }
        
        public UserSessionServiceRemoveTimeZoneResponse(System.DateTime response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceApplyTimeZoneRequest", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceApplyTimeZoneRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public AxRetailSOAPI.AxUserSeccion.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public System.DateTime dateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=1)]
        public int timeZoneOffset;
        
        public UserSessionServiceApplyTimeZoneRequest() {
        }
        
        public UserSessionServiceApplyTimeZoneRequest(AxRetailSOAPI.AxUserSeccion.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset) {
            this.CallContext = CallContext;
            this.dateTime = dateTime;
            this.timeZoneOffset = timeZoneOffset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSessionServiceApplyTimeZoneResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class UserSessionServiceApplyTimeZoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public System.DateTime response;
        
        public UserSessionServiceApplyTimeZoneResponse() {
        }
        
        public UserSessionServiceApplyTimeZoneResponse(System.DateTime response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserSessionServiceChannel : AxRetailSOAPI.AxUserSeccion.UserSessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserSessionServiceClient : System.ServiceModel.ClientBase<AxRetailSOAPI.AxUserSeccion.UserSessionService>, AxRetailSOAPI.AxUserSeccion.UserSessionService {
        
        public UserSessionServiceClient() {
        }
        
        public UserSessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserSessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSessionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyResponse AxRetailSOAPI.AxUserSeccion.UserSessionService.GetPartitionKey(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyRequest request) {
            return base.Channel.GetPartitionKey(request);
        }
        
        public string GetPartitionKey(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyRequest();
            inValue.CallContext = CallContext;
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyResponse retVal = ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).GetPartitionKey(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyResponse> AxRetailSOAPI.AxUserSeccion.UserSessionService.GetPartitionKeyAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyRequest request) {
            return base.Channel.GetPartitionKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyResponse> GetPartitionKeyAsync(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeyRequest();
            inValue.CallContext = CallContext;
            return ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).GetPartitionKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserResponse AxRetailSOAPI.AxUserSeccion.UserSessionService.GetPartitionKeysForUser(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserRequest request) {
            return base.Channel.GetPartitionKeysForUser(request);
        }
        
        public string[] GetPartitionKeysForUser(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserRequest();
            inValue.CallContext = CallContext;
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserResponse retVal = ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).GetPartitionKeysForUser(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserResponse> AxRetailSOAPI.AxUserSeccion.UserSessionService.GetPartitionKeysForUserAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserRequest request) {
            return base.Channel.GetPartitionKeysForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserResponse> GetPartitionKeysForUserAsync(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetPartitionKeysForUserRequest();
            inValue.CallContext = CallContext;
            return ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).GetPartitionKeysForUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsResponse AxRetailSOAPI.AxUserSeccion.UserSessionService.GetAccessRights(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsRequest request) {
            return base.Channel.GetAccessRights(request);
        }
        
        public AxRetailSOAPI.AxUserSeccion.AccessRight[] GetAccessRights(AxRetailSOAPI.AxUserSeccion.CallContext CallContext, AxRetailSOAPI.AxUserSeccion.AccessControlledItemKey[] _keys) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsRequest();
            inValue.CallContext = CallContext;
            inValue._keys = _keys;
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsResponse retVal = ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).GetAccessRights(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsResponse> AxRetailSOAPI.AxUserSeccion.UserSessionService.GetAccessRightsAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsRequest request) {
            return base.Channel.GetAccessRightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsResponse> GetAccessRightsAsync(AxRetailSOAPI.AxUserSeccion.CallContext CallContext, AxRetailSOAPI.AxUserSeccion.AccessControlledItemKey[] _keys) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetAccessRightsRequest();
            inValue.CallContext = CallContext;
            inValue._keys = _keys;
            return ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).GetAccessRightsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoResponse AxRetailSOAPI.AxUserSeccion.UserSessionService.GetUserSessionInfo(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoRequest request) {
            return base.Channel.GetUserSessionInfo(request);
        }
        
        public AxRetailSOAPI.AxUserSeccion.UserSessionInfo GetUserSessionInfo(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoRequest();
            inValue.CallContext = CallContext;
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoResponse retVal = ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).GetUserSessionInfo(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoResponse> AxRetailSOAPI.AxUserSeccion.UserSessionService.GetUserSessionInfoAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoRequest request) {
            return base.Channel.GetUserSessionInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoResponse> GetUserSessionInfoAsync(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceGetUserSessionInfoRequest();
            inValue.CallContext = CallContext;
            return ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).GetUserSessionInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemResponse AxRetailSOAPI.AxUserSeccion.UserSessionService.IsSinglePartitionSystem(AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemRequest request) {
            return base.Channel.IsSinglePartitionSystem(request);
        }
        
        public bool IsSinglePartitionSystem(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemRequest();
            inValue.CallContext = CallContext;
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemResponse retVal = ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).IsSinglePartitionSystem(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemResponse> AxRetailSOAPI.AxUserSeccion.UserSessionService.IsSinglePartitionSystemAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemRequest request) {
            return base.Channel.IsSinglePartitionSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemResponse> IsSinglePartitionSystemAsync(AxRetailSOAPI.AxUserSeccion.CallContext CallContext) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceIsSinglePartitionSystemRequest();
            inValue.CallContext = CallContext;
            return ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).IsSinglePartitionSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneResponse AxRetailSOAPI.AxUserSeccion.UserSessionService.RemoveTimeZone(AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneRequest request) {
            return base.Channel.RemoveTimeZone(request);
        }
        
        public System.DateTime RemoveTimeZone(AxRetailSOAPI.AxUserSeccion.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneRequest();
            inValue.CallContext = CallContext;
            inValue.dateTime = dateTime;
            inValue.timeZoneOffset = timeZoneOffset;
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneResponse retVal = ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).RemoveTimeZone(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneResponse> AxRetailSOAPI.AxUserSeccion.UserSessionService.RemoveTimeZoneAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneRequest request) {
            return base.Channel.RemoveTimeZoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneResponse> RemoveTimeZoneAsync(AxRetailSOAPI.AxUserSeccion.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceRemoveTimeZoneRequest();
            inValue.CallContext = CallContext;
            inValue.dateTime = dateTime;
            inValue.timeZoneOffset = timeZoneOffset;
            return ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).RemoveTimeZoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneResponse AxRetailSOAPI.AxUserSeccion.UserSessionService.ApplyTimeZone(AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneRequest request) {
            return base.Channel.ApplyTimeZone(request);
        }
        
        public System.DateTime ApplyTimeZone(AxRetailSOAPI.AxUserSeccion.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneRequest();
            inValue.CallContext = CallContext;
            inValue.dateTime = dateTime;
            inValue.timeZoneOffset = timeZoneOffset;
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneResponse retVal = ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).ApplyTimeZone(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneResponse> AxRetailSOAPI.AxUserSeccion.UserSessionService.ApplyTimeZoneAsync(AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneRequest request) {
            return base.Channel.ApplyTimeZoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneResponse> ApplyTimeZoneAsync(AxRetailSOAPI.AxUserSeccion.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset) {
            AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneRequest inValue = new AxRetailSOAPI.AxUserSeccion.UserSessionServiceApplyTimeZoneRequest();
            inValue.CallContext = CallContext;
            inValue.dateTime = dateTime;
            inValue.timeZoneOffset = timeZoneOffset;
            return ((AxRetailSOAPI.AxUserSeccion.UserSessionService)(this)).ApplyTimeZoneAsync(inValue);
        }
    }
}
