//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxRetailSOAPI.AxRetailSOLog {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customDetailXmlField;
        
        private FaultMessageList[] faultMessageListArrayField;
        
        private InfologMessage[] infologMessageListField;
        
        private string stackTraceField;
        
        private int xppExceptionTypeField;
        
        private bool xppExceptionTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CustomDetailXml {
            get {
                return this.customDetailXmlField;
            }
            set {
                this.customDetailXmlField = value;
                this.RaisePropertyChanged("CustomDetailXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public FaultMessageList[] FaultMessageListArray {
            get {
                return this.faultMessageListArrayField;
            }
            set {
                this.faultMessageListArrayField = value;
                this.RaisePropertyChanged("FaultMessageListArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
        public InfologMessage[] InfologMessageList {
            get {
                return this.infologMessageListField;
            }
            set {
                this.infologMessageListField = value;
                this.RaisePropertyChanged("InfologMessageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int XppExceptionType {
            get {
                return this.xppExceptionTypeField;
            }
            set {
                this.xppExceptionTypeField = value;
                this.RaisePropertyChanged("XppExceptionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XppExceptionTypeSpecified {
            get {
                return this.xppExceptionTypeFieldSpecified;
            }
            set {
                this.xppExceptionTypeFieldSpecified = value;
                this.RaisePropertyChanged("XppExceptionTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentField;
        
        private string documentOperationField;
        
        private FaultMessage[] faultMessageArrayField;
        
        private string fieldField;
        
        private string serviceField;
        
        private string serviceOperationField;
        
        private string serviceOperationParameterField;
        
        private string xPathField;
        
        private string xmlLineField;
        
        private string xmlPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DocumentOperation {
            get {
                return this.documentOperationField;
            }
            set {
                this.documentOperationField = value;
                this.RaisePropertyChanged("DocumentOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public FaultMessage[] FaultMessageArray {
            get {
                return this.faultMessageArrayField;
            }
            set {
                this.faultMessageArrayField = value;
                this.RaisePropertyChanged("FaultMessageArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ServiceOperation {
            get {
                return this.serviceOperationField;
            }
            set {
                this.serviceOperationField = value;
                this.RaisePropertyChanged("ServiceOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ServiceOperationParameter {
            get {
                return this.serviceOperationParameterField;
            }
            set {
                this.serviceOperationParameterField = value;
                this.RaisePropertyChanged("ServiceOperationParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
                this.RaisePropertyChanged("XPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string XmlLine {
            get {
                return this.xmlLineField;
            }
            set {
                this.xmlLineField = value;
                this.RaisePropertyChanged("XmlLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string XmlPosition {
            get {
                return this.xmlPositionField;
            }
            set {
                this.xmlPositionField = value;
                this.RaisePropertyChanged("XmlPosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfologMessageType infologMessageTypeField;
        
        private bool infologMessageTypeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfologMessageType InfologMessageType {
            get {
                return this.infologMessageTypeField;
            }
            set {
                this.infologMessageTypeField = value;
                this.RaisePropertyChanged("InfologMessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfologMessageTypeSpecified {
            get {
                return this.infologMessageTypeFieldSpecified;
            }
            set {
                this.infologMessageTypeFieldSpecified = value;
                this.RaisePropertyChanged("InfologMessageTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType {
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/AxdSTMSalesSoLog")]
    public partial class AxdEntity_StmSalesSoLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _DocumentHashField;
        
        private string createByField;
        
        private string modifyByField;
        
        private System.Nullable<long> recIdField;
        
        private bool recIdFieldSpecified;
        
        private System.Nullable<int> recVersionField;
        
        private bool recVersionFieldSpecified;
        
        private System.Nullable<long> refRecIdField;
        
        private bool refRecIdFieldSpecified;
        
        private string classField;
        
        private AxdEnum_AxdEntityAction actionField;
        
        private bool actionFieldSpecified;
        
        public AxdEntity_StmSalesSoLog() {
            this.classField = "entity";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string _DocumentHash {
            get {
                return this._DocumentHashField;
            }
            set {
                this._DocumentHashField = value;
                this.RaisePropertyChanged("_DocumentHash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string CreateBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
                this.RaisePropertyChanged("CreateBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ModifyBy {
            get {
                return this.modifyByField;
            }
            set {
                this.modifyByField = value;
                this.RaisePropertyChanged("ModifyBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> RecId {
            get {
                return this.recIdField;
            }
            set {
                this.recIdField = value;
                this.RaisePropertyChanged("RecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecIdSpecified {
            get {
                return this.recIdFieldSpecified;
            }
            set {
                this.recIdFieldSpecified = value;
                this.RaisePropertyChanged("RecIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> RecVersion {
            get {
                return this.recVersionField;
            }
            set {
                this.recVersionField = value;
                this.RaisePropertyChanged("RecVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecVersionSpecified {
            get {
                return this.recVersionFieldSpecified;
            }
            set {
                this.recVersionFieldSpecified = value;
                this.RaisePropertyChanged("RecVersionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> RefRecId {
            get {
                return this.refRecIdField;
            }
            set {
                this.refRecIdField = value;
                this.RaisePropertyChanged("RefRecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RefRecIdSpecified {
            get {
                return this.refRecIdFieldSpecified;
            }
            set {
                this.refRecIdFieldSpecified = value;
                this.RaisePropertyChanged("RefRecIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AxdEnum_AxdEntityAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_AxdEntityAction {
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        replace,
        
        /// <remarks/>
        delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/AxdSTMSalesSoLog")]
    public partial class AxdAxdSTMSalesSoLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<AxdEnum_boolean> clearNilFieldsOnUpdateField;
        
        private bool clearNilFieldsOnUpdateFieldSpecified;
        
        private System.Nullable<AxdEnum_XMLDocPurpose> docPurposeField;
        
        private bool docPurposeFieldSpecified;
        
        private string senderIdField;
        
        private AxdEntity_StmSalesSoLog[] stmSalesSoLogField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<AxdEnum_boolean> ClearNilFieldsOnUpdate {
            get {
                return this.clearNilFieldsOnUpdateField;
            }
            set {
                this.clearNilFieldsOnUpdateField = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearNilFieldsOnUpdateSpecified {
            get {
                return this.clearNilFieldsOnUpdateFieldSpecified;
            }
            set {
                this.clearNilFieldsOnUpdateFieldSpecified = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<AxdEnum_XMLDocPurpose> DocPurpose {
            get {
                return this.docPurposeField;
            }
            set {
                this.docPurposeField = value;
                this.RaisePropertyChanged("DocPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocPurposeSpecified {
            get {
                return this.docPurposeFieldSpecified;
            }
            set {
                this.docPurposeFieldSpecified = value;
                this.RaisePropertyChanged("DocPurposeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("SenderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StmSalesSoLog", Order=3)]
        public AxdEntity_StmSalesSoLog[] StmSalesSoLog {
            get {
                return this.stmSalesSoLogField;
            }
            set {
                this.stmSalesSoLogField = value;
                this.RaisePropertyChanged("StmSalesSoLog");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_boolean {
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        @true,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_XMLDocPurpose {
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        Duplicate,
        
        /// <remarks/>
        Proforma,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class CriteriaElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataSourceNameField;
        
        private string fieldNameField;
        
        private Operator operatorField;
        
        private string value1Field;
        
        private string value2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                this.dataSourceNameField = value;
                this.RaisePropertyChanged("DataSourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Operator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
                this.RaisePropertyChanged("Value1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
                this.RaisePropertyChanged("Value2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public enum Operator {
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Range,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class QueryCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CriteriaElement[] criteriaElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CriteriaElement", Order=0)]
        public CriteriaElement[] CriteriaElement {
            get {
                return this.criteriaElementField;
            }
            set {
                this.criteriaElementField = value;
                this.RaisePropertyChanged("CriteriaElement");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="AxRetailSOLog.AxdSTMSalesSoLogService")]
    public interface AxdSTMSalesSoLogService {
        
        // CODEGEN: Generating message contract since the wrapper name (AxdSTMSalesSoLogServiceFindRequest) of message AxdSTMSalesSoLogServiceFindRequest does not match the default value (find)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AxdSTMSalesSoLogService/find", ReplyAction="http://tempuri.org/AxdSTMSalesSoLogService/findResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSOLog.AifFault), Action="http://tempuri.org/AxdSTMSalesSoLogService/findAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindResponse find(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AxdSTMSalesSoLogService/find", ReplyAction="http://tempuri.org/AxdSTMSalesSoLogService/findResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindResponse> findAsync(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (AxdSTMSalesSoLogServiceReadRequest) of message AxdSTMSalesSoLogServiceReadRequest does not match the default value (read)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AxdSTMSalesSoLogService/read", ReplyAction="http://tempuri.org/AxdSTMSalesSoLogService/readResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSOLog.AifFault), Action="http://tempuri.org/AxdSTMSalesSoLogService/readAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadResponse read(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AxdSTMSalesSoLogService/read", ReplyAction="http://tempuri.org/AxdSTMSalesSoLogService/readResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadResponse> readAsync(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (AxdSTMSalesSoLogServiceCreateRequest) of message AxdSTMSalesSoLogServiceCreateRequest does not match the default value (create)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AxdSTMSalesSoLogService/create", ReplyAction="http://tempuri.org/AxdSTMSalesSoLogService/createResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSOLog.AifFault), Action="http://tempuri.org/AxdSTMSalesSoLogService/createAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateResponse create(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AxdSTMSalesSoLogService/create", ReplyAction="http://tempuri.org/AxdSTMSalesSoLogService/createResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateResponse> createAsync(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyField;
        
        private string languageField;
        
        private string logonAsUserField;
        
        private string messageIdField;
        
        private string partitionKeyField;
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] propertyBagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LogonAsUser {
            get {
                return this.logonAsUserField;
            }
            set {
                this.logonAsUserField = value;
                this.RaisePropertyChanged("LogonAsUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string PartitionKey {
            get {
                return this.partitionKeyField;
            }
            set {
                this.partitionKeyField = value;
                this.RaisePropertyChanged("PartitionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] PropertyBag {
            get {
                return this.propertyBagField;
            }
            set {
                this.propertyBagField = value;
                this.RaisePropertyChanged("PropertyBag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AxdSTMSalesSoLogServiceFindRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class AxdSTMSalesSoLogServiceFindRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSOLog.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
        public AxRetailSOAPI.AxRetailSOLog.QueryCriteria QueryCriteria;
        
        public AxdSTMSalesSoLogServiceFindRequest() {
        }
        
        public AxdSTMSalesSoLogServiceFindRequest(AxRetailSOAPI.AxRetailSOLog.CallContext CallContext, AxRetailSOAPI.AxRetailSOLog.QueryCriteria QueryCriteria) {
            this.CallContext = CallContext;
            this.QueryCriteria = QueryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AxdSTMSalesSoLogServiceFindResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class AxdSTMSalesSoLogServiceFindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/AxdSTMSalesSoLog", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/AxdSTMSalesSoLog")]
        public AxRetailSOAPI.AxRetailSOLog.AxdAxdSTMSalesSoLog AxdSTMSalesSoLog;
        
        public AxdSTMSalesSoLogServiceFindResponse() {
        }
        
        public AxdSTMSalesSoLogServiceFindResponse(AxRetailSOAPI.AxRetailSOLog.AxdAxdSTMSalesSoLog AxdSTMSalesSoLog) {
            this.AxdSTMSalesSoLog = AxdSTMSalesSoLog;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyField[] keyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyField[] KeyData {
            get {
                return this.keyDataField;
            }
            set {
                this.keyDataField = value;
                this.RaisePropertyChanged("KeyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class KeyField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AxdSTMSalesSoLogServiceReadRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class AxdSTMSalesSoLogServiceReadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSOLog.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public AxRetailSOAPI.AxRetailSOLog.EntityKey[] EntityKeyList;
        
        public AxdSTMSalesSoLogServiceReadRequest() {
        }
        
        public AxdSTMSalesSoLogServiceReadRequest(AxRetailSOAPI.AxRetailSOLog.CallContext CallContext, AxRetailSOAPI.AxRetailSOLog.EntityKey[] EntityKeyList) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AxdSTMSalesSoLogServiceReadResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class AxdSTMSalesSoLogServiceReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/AxdSTMSalesSoLog", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/AxdSTMSalesSoLog")]
        public AxRetailSOAPI.AxRetailSOLog.AxdAxdSTMSalesSoLog AxdSTMSalesSoLog;
        
        public AxdSTMSalesSoLogServiceReadResponse() {
        }
        
        public AxdSTMSalesSoLogServiceReadResponse(AxRetailSOAPI.AxRetailSOLog.AxdAxdSTMSalesSoLog AxdSTMSalesSoLog) {
            this.AxdSTMSalesSoLog = AxdSTMSalesSoLog;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AxdSTMSalesSoLogServiceCreateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class AxdSTMSalesSoLogServiceCreateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSOLog.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/AxdSTMSalesSoLog", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/AxdSTMSalesSoLog")]
        public AxRetailSOAPI.AxRetailSOLog.AxdAxdSTMSalesSoLog AxdSTMSalesSoLog;
        
        public AxdSTMSalesSoLogServiceCreateRequest() {
        }
        
        public AxdSTMSalesSoLogServiceCreateRequest(AxRetailSOAPI.AxRetailSOLog.CallContext CallContext, AxRetailSOAPI.AxRetailSOLog.AxdAxdSTMSalesSoLog AxdSTMSalesSoLog) {
            this.CallContext = CallContext;
            this.AxdSTMSalesSoLog = AxdSTMSalesSoLog;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AxdSTMSalesSoLogServiceCreateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class AxdSTMSalesSoLogServiceCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public AxRetailSOAPI.AxRetailSOLog.EntityKey[] EntityKeyList;
        
        public AxdSTMSalesSoLogServiceCreateResponse() {
        }
        
        public AxdSTMSalesSoLogServiceCreateResponse(AxRetailSOAPI.AxRetailSOLog.EntityKey[] EntityKeyList) {
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AxdSTMSalesSoLogServiceChannel : AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AxdSTMSalesSoLogServiceClient : System.ServiceModel.ClientBase<AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService>, AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService {
        
        public AxdSTMSalesSoLogServiceClient() {
        }
        
        public AxdSTMSalesSoLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AxdSTMSalesSoLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AxdSTMSalesSoLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AxdSTMSalesSoLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindResponse AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService.find(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindRequest request) {
            return base.Channel.find(request);
        }
        
        public AxRetailSOAPI.AxRetailSOLog.AxdAxdSTMSalesSoLog find(AxRetailSOAPI.AxRetailSOLog.CallContext CallContext, AxRetailSOAPI.AxRetailSOLog.QueryCriteria QueryCriteria) {
            AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindRequest inValue = new AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindResponse retVal = ((AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService)(this)).find(inValue);
            return retVal.AxdSTMSalesSoLog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindResponse> AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService.findAsync(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindRequest request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindResponse> findAsync(AxRetailSOAPI.AxRetailSOLog.CallContext CallContext, AxRetailSOAPI.AxRetailSOLog.QueryCriteria QueryCriteria) {
            AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindRequest inValue = new AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            return ((AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadResponse AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService.read(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadRequest request) {
            return base.Channel.read(request);
        }
        
        public AxRetailSOAPI.AxRetailSOLog.AxdAxdSTMSalesSoLog read(AxRetailSOAPI.AxRetailSOLog.CallContext CallContext, AxRetailSOAPI.AxRetailSOLog.EntityKey[] EntityKeyList) {
            AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadRequest inValue = new AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadResponse retVal = ((AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService)(this)).read(inValue);
            return retVal.AxdSTMSalesSoLog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadResponse> AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService.readAsync(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadRequest request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadResponse> readAsync(AxRetailSOAPI.AxRetailSOLog.CallContext CallContext, AxRetailSOAPI.AxRetailSOLog.EntityKey[] EntityKeyList) {
            AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadRequest inValue = new AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            return ((AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateResponse AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService.create(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateRequest request) {
            return base.Channel.create(request);
        }
        
        public AxRetailSOAPI.AxRetailSOLog.EntityKey[] create(AxRetailSOAPI.AxRetailSOLog.CallContext CallContext, AxRetailSOAPI.AxRetailSOLog.AxdAxdSTMSalesSoLog AxdSTMSalesSoLog) {
            AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateRequest inValue = new AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateRequest();
            inValue.CallContext = CallContext;
            inValue.AxdSTMSalesSoLog = AxdSTMSalesSoLog;
            AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateResponse retVal = ((AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService)(this)).create(inValue);
            return retVal.EntityKeyList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateResponse> AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService.createAsync(AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateRequest request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateResponse> createAsync(AxRetailSOAPI.AxRetailSOLog.CallContext CallContext, AxRetailSOAPI.AxRetailSOLog.AxdAxdSTMSalesSoLog AxdSTMSalesSoLog) {
            AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateRequest inValue = new AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogServiceCreateRequest();
            inValue.CallContext = CallContext;
            inValue.AxdSTMSalesSoLog = AxdSTMSalesSoLog;
            return ((AxRetailSOAPI.AxRetailSOLog.AxdSTMSalesSoLogService)(this)).createAsync(inValue);
        }
    }
}
