//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxRetailSOAPI.AxRetailSOLine {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customDetailXmlField;
        
        private FaultMessageList[] faultMessageListArrayField;
        
        private InfologMessage[] infologMessageListField;
        
        private string stackTraceField;
        
        private int xppExceptionTypeField;
        
        private bool xppExceptionTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CustomDetailXml {
            get {
                return this.customDetailXmlField;
            }
            set {
                this.customDetailXmlField = value;
                this.RaisePropertyChanged("CustomDetailXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public FaultMessageList[] FaultMessageListArray {
            get {
                return this.faultMessageListArrayField;
            }
            set {
                this.faultMessageListArrayField = value;
                this.RaisePropertyChanged("FaultMessageListArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
        public InfologMessage[] InfologMessageList {
            get {
                return this.infologMessageListField;
            }
            set {
                this.infologMessageListField = value;
                this.RaisePropertyChanged("InfologMessageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int XppExceptionType {
            get {
                return this.xppExceptionTypeField;
            }
            set {
                this.xppExceptionTypeField = value;
                this.RaisePropertyChanged("XppExceptionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XppExceptionTypeSpecified {
            get {
                return this.xppExceptionTypeFieldSpecified;
            }
            set {
                this.xppExceptionTypeFieldSpecified = value;
                this.RaisePropertyChanged("XppExceptionTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentField;
        
        private string documentOperationField;
        
        private FaultMessage[] faultMessageArrayField;
        
        private string fieldField;
        
        private string serviceField;
        
        private string serviceOperationField;
        
        private string serviceOperationParameterField;
        
        private string xPathField;
        
        private string xmlLineField;
        
        private string xmlPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DocumentOperation {
            get {
                return this.documentOperationField;
            }
            set {
                this.documentOperationField = value;
                this.RaisePropertyChanged("DocumentOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public FaultMessage[] FaultMessageArray {
            get {
                return this.faultMessageArrayField;
            }
            set {
                this.faultMessageArrayField = value;
                this.RaisePropertyChanged("FaultMessageArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ServiceOperation {
            get {
                return this.serviceOperationField;
            }
            set {
                this.serviceOperationField = value;
                this.RaisePropertyChanged("ServiceOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ServiceOperationParameter {
            get {
                return this.serviceOperationParameterField;
            }
            set {
                this.serviceOperationParameterField = value;
                this.RaisePropertyChanged("ServiceOperationParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
                this.RaisePropertyChanged("XPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string XmlLine {
            get {
                return this.xmlLineField;
            }
            set {
                this.xmlLineField = value;
                this.RaisePropertyChanged("XmlLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string XmlPosition {
            get {
                return this.xmlPositionField;
            }
            set {
                this.xmlPositionField = value;
                this.RaisePropertyChanged("XmlPosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfologMessageType infologMessageTypeField;
        
        private bool infologMessageTypeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfologMessageType InfologMessageType {
            get {
                return this.infologMessageTypeField;
            }
            set {
                this.infologMessageTypeField = value;
                this.RaisePropertyChanged("InfologMessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfologMessageTypeSpecified {
            get {
                return this.infologMessageTypeFieldSpecified;
            }
            set {
                this.infologMessageTypeFieldSpecified = value;
                this.RaisePropertyChanged("InfologMessageTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType {
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMSODailyLine")]
    public partial class AxdEntity_StmSalesSoDailyLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _DocumentHashField;
        
        private string modelField;
        
        private System.Nullable<long> recIdField;
        
        private bool recIdFieldSpecified;
        
        private System.Nullable<int> recVersionField;
        
        private bool recVersionFieldSpecified;
        
        private System.Nullable<decimal> salesAmountField;
        
        private bool salesAmountFieldSpecified;
        
        private System.Nullable<System.DateTime> salesDateField;
        
        private bool salesDateFieldSpecified;
        
        private System.Nullable<long> salesOrderDailyField;
        
        private bool salesOrderDailyFieldSpecified;
        
        private string salesPoolIdField;
        
        private System.Nullable<decimal> salesQtyField;
        
        private bool salesQtyFieldSpecified;
        
        private string seriesField;
        
        private string sinkField;
        
        private string stmStoreIdField;
        
        private string classField;
        
        private AxdEnum_AxdEntityAction actionField;
        
        private bool actionFieldSpecified;
        
        public AxdEntity_StmSalesSoDailyLine() {
            this.classField = "entity";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string _DocumentHash {
            get {
                return this._DocumentHashField;
            }
            set {
                this._DocumentHashField = value;
                this.RaisePropertyChanged("_DocumentHash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("Model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> RecId {
            get {
                return this.recIdField;
            }
            set {
                this.recIdField = value;
                this.RaisePropertyChanged("RecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecIdSpecified {
            get {
                return this.recIdFieldSpecified;
            }
            set {
                this.recIdFieldSpecified = value;
                this.RaisePropertyChanged("RecIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> RecVersion {
            get {
                return this.recVersionField;
            }
            set {
                this.recVersionField = value;
                this.RaisePropertyChanged("RecVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecVersionSpecified {
            get {
                return this.recVersionFieldSpecified;
            }
            set {
                this.recVersionFieldSpecified = value;
                this.RaisePropertyChanged("RecVersionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> SalesAmount {
            get {
                return this.salesAmountField;
            }
            set {
                this.salesAmountField = value;
                this.RaisePropertyChanged("SalesAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesAmountSpecified {
            get {
                return this.salesAmountFieldSpecified;
            }
            set {
                this.salesAmountFieldSpecified = value;
                this.RaisePropertyChanged("SalesAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> SalesDate {
            get {
                return this.salesDateField;
            }
            set {
                this.salesDateField = value;
                this.RaisePropertyChanged("SalesDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesDateSpecified {
            get {
                return this.salesDateFieldSpecified;
            }
            set {
                this.salesDateFieldSpecified = value;
                this.RaisePropertyChanged("SalesDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> SalesOrderDaily {
            get {
                return this.salesOrderDailyField;
            }
            set {
                this.salesOrderDailyField = value;
                this.RaisePropertyChanged("SalesOrderDaily");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesOrderDailySpecified {
            get {
                return this.salesOrderDailyFieldSpecified;
            }
            set {
                this.salesOrderDailyFieldSpecified = value;
                this.RaisePropertyChanged("SalesOrderDailySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string SalesPoolId {
            get {
                return this.salesPoolIdField;
            }
            set {
                this.salesPoolIdField = value;
                this.RaisePropertyChanged("SalesPoolId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> SalesQty {
            get {
                return this.salesQtyField;
            }
            set {
                this.salesQtyField = value;
                this.RaisePropertyChanged("SalesQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesQtySpecified {
            get {
                return this.salesQtyFieldSpecified;
            }
            set {
                this.salesQtyFieldSpecified = value;
                this.RaisePropertyChanged("SalesQtySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string Series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
                this.RaisePropertyChanged("Series");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string Sink {
            get {
                return this.sinkField;
            }
            set {
                this.sinkField = value;
                this.RaisePropertyChanged("Sink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string StmStoreId {
            get {
                return this.stmStoreIdField;
            }
            set {
                this.stmStoreIdField = value;
                this.RaisePropertyChanged("StmStoreId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AxdEnum_AxdEntityAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_AxdEntityAction {
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        replace,
        
        /// <remarks/>
        delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMSODailyLine")]
    public partial class AxdSTMSODailyLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<AxdEnum_boolean> clearNilFieldsOnUpdateField;
        
        private bool clearNilFieldsOnUpdateFieldSpecified;
        
        private System.Nullable<AxdEnum_XMLDocPurpose> docPurposeField;
        
        private bool docPurposeFieldSpecified;
        
        private string senderIdField;
        
        private AxdEntity_StmSalesSoDailyLine[] stmSalesSoDailyLineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<AxdEnum_boolean> ClearNilFieldsOnUpdate {
            get {
                return this.clearNilFieldsOnUpdateField;
            }
            set {
                this.clearNilFieldsOnUpdateField = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearNilFieldsOnUpdateSpecified {
            get {
                return this.clearNilFieldsOnUpdateFieldSpecified;
            }
            set {
                this.clearNilFieldsOnUpdateFieldSpecified = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<AxdEnum_XMLDocPurpose> DocPurpose {
            get {
                return this.docPurposeField;
            }
            set {
                this.docPurposeField = value;
                this.RaisePropertyChanged("DocPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocPurposeSpecified {
            get {
                return this.docPurposeFieldSpecified;
            }
            set {
                this.docPurposeFieldSpecified = value;
                this.RaisePropertyChanged("DocPurposeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("SenderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StmSalesSoDailyLine", Order=3)]
        public AxdEntity_StmSalesSoDailyLine[] StmSalesSoDailyLine {
            get {
                return this.stmSalesSoDailyLineField;
            }
            set {
                this.stmSalesSoDailyLineField = value;
                this.RaisePropertyChanged("StmSalesSoDailyLine");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_boolean {
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        @true,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_XMLDocPurpose {
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        Duplicate,
        
        /// <remarks/>
        Proforma,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class KeyField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyField[] keyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyField[] KeyData {
            get {
                return this.keyDataField;
            }
            set {
                this.keyDataField = value;
                this.RaisePropertyChanged("KeyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="AxRetailSOLine.STMSODailyLineService")]
    public interface STMSODailyLineService {
        
        // CODEGEN: Generating message contract since the wrapper name (STMSODailyLineServiceReadRequest) of message STMSODailyLineServiceReadRequest does not match the default value (read)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMSODailyLineService/read", ReplyAction="http://tempuri.org/STMSODailyLineService/readResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSOLine.AifFault), Action="http://tempuri.org/STMSODailyLineService/readAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadResponse read(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMSODailyLineService/read", ReplyAction="http://tempuri.org/STMSODailyLineService/readResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadResponse> readAsync(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (STMSODailyLineServiceDeleteRequest) of message STMSODailyLineServiceDeleteRequest does not match the default value (delete)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMSODailyLineService/delete", ReplyAction="http://tempuri.org/STMSODailyLineService/deleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSOLine.AifFault), Action="http://tempuri.org/STMSODailyLineService/deleteAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteResponse delete(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMSODailyLineService/delete", ReplyAction="http://tempuri.org/STMSODailyLineService/deleteResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteResponse> deleteAsync(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (STMSODailyLineServiceFindRequest) of message STMSODailyLineServiceFindRequest does not match the default value (find)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMSODailyLineService/find", ReplyAction="http://tempuri.org/STMSODailyLineService/findResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSOLine.AifFault), Action="http://tempuri.org/STMSODailyLineService/findAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindResponse find(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMSODailyLineService/find", ReplyAction="http://tempuri.org/STMSODailyLineService/findResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindResponse> findAsync(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (STMSODailyLineServiceUpdateRequest) of message STMSODailyLineServiceUpdateRequest does not match the default value (update)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMSODailyLineService/update", ReplyAction="http://tempuri.org/STMSODailyLineService/updateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSOLine.AifFault), Action="http://tempuri.org/STMSODailyLineService/updateAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateResponse update(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMSODailyLineService/update", ReplyAction="http://tempuri.org/STMSODailyLineService/updateResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateResponse> updateAsync(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (STMSODailyLineServiceCreateRequest) of message STMSODailyLineServiceCreateRequest does not match the default value (create)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMSODailyLineService/create", ReplyAction="http://tempuri.org/STMSODailyLineService/createResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSOLine.AifFault), Action="http://tempuri.org/STMSODailyLineService/createAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateResponse create(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMSODailyLineService/create", ReplyAction="http://tempuri.org/STMSODailyLineService/createResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateResponse> createAsync(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyField;
        
        private string languageField;
        
        private string logonAsUserField;
        
        private string messageIdField;
        
        private string partitionKeyField;
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] propertyBagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LogonAsUser {
            get {
                return this.logonAsUserField;
            }
            set {
                this.logonAsUserField = value;
                this.RaisePropertyChanged("LogonAsUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string PartitionKey {
            get {
                return this.partitionKeyField;
            }
            set {
                this.partitionKeyField = value;
                this.RaisePropertyChanged("PartitionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] PropertyBag {
            get {
                return this.propertyBagField;
            }
            set {
                this.propertyBagField = value;
                this.RaisePropertyChanged("PropertyBag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMSODailyLineServiceReadRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMSODailyLineServiceReadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSOLine.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList;
        
        public STMSODailyLineServiceReadRequest() {
        }
        
        public STMSODailyLineServiceReadRequest(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMSODailyLineServiceReadResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMSODailyLineServiceReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMSODailyLine", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMSODailyLine")]
        public AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine;
        
        public STMSODailyLineServiceReadResponse() {
        }
        
        public STMSODailyLineServiceReadResponse(AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine) {
            this.STMSODailyLine = STMSODailyLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMSODailyLineServiceDeleteRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMSODailyLineServiceDeleteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSOLine.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList;
        
        public STMSODailyLineServiceDeleteRequest() {
        }
        
        public STMSODailyLineServiceDeleteRequest(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMSODailyLineServiceDeleteResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMSODailyLineServiceDeleteResponse {
        
        public STMSODailyLineServiceDeleteResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class QueryCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CriteriaElement[] criteriaElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CriteriaElement", Order=0)]
        public CriteriaElement[] CriteriaElement {
            get {
                return this.criteriaElementField;
            }
            set {
                this.criteriaElementField = value;
                this.RaisePropertyChanged("CriteriaElement");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class CriteriaElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataSourceNameField;
        
        private string fieldNameField;
        
        private Operator operatorField;
        
        private string value1Field;
        
        private string value2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                this.dataSourceNameField = value;
                this.RaisePropertyChanged("DataSourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Operator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
                this.RaisePropertyChanged("Value1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
                this.RaisePropertyChanged("Value2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public enum Operator {
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Range,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMSODailyLineServiceFindRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMSODailyLineServiceFindRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSOLine.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
        public AxRetailSOAPI.AxRetailSOLine.QueryCriteria QueryCriteria;
        
        public STMSODailyLineServiceFindRequest() {
        }
        
        public STMSODailyLineServiceFindRequest(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.QueryCriteria QueryCriteria) {
            this.CallContext = CallContext;
            this.QueryCriteria = QueryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMSODailyLineServiceFindResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMSODailyLineServiceFindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMSODailyLine", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMSODailyLine")]
        public AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine;
        
        public STMSODailyLineServiceFindResponse() {
        }
        
        public STMSODailyLineServiceFindResponse(AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine) {
            this.STMSODailyLine = STMSODailyLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMSODailyLineServiceUpdateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMSODailyLineServiceUpdateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSOLine.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMSODailyLine", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMSODailyLine")]
        public AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine;
        
        public STMSODailyLineServiceUpdateRequest() {
        }
        
        public STMSODailyLineServiceUpdateRequest(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList, AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
            this.STMSODailyLine = STMSODailyLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMSODailyLineServiceUpdateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMSODailyLineServiceUpdateResponse {
        
        public STMSODailyLineServiceUpdateResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMSODailyLineServiceCreateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMSODailyLineServiceCreateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSOLine.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMSODailyLine", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMSODailyLine")]
        public AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine;
        
        public STMSODailyLineServiceCreateRequest() {
        }
        
        public STMSODailyLineServiceCreateRequest(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine) {
            this.CallContext = CallContext;
            this.STMSODailyLine = STMSODailyLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMSODailyLineServiceCreateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMSODailyLineServiceCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList;
        
        public STMSODailyLineServiceCreateResponse() {
        }
        
        public STMSODailyLineServiceCreateResponse(AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList) {
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface STMSODailyLineServiceChannel : AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class STMSODailyLineServiceClient : System.ServiceModel.ClientBase<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService>, AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService {
        
        public STMSODailyLineServiceClient() {
        }
        
        public STMSODailyLineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public STMSODailyLineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public STMSODailyLineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public STMSODailyLineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadResponse AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService.read(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadRequest request) {
            return base.Channel.read(request);
        }
        
        public AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine read(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList) {
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadRequest inValue = new AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadResponse retVal = ((AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService)(this)).read(inValue);
            return retVal.STMSODailyLine;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadResponse> AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService.readAsync(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadRequest request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadResponse> readAsync(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList) {
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadRequest inValue = new AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            return ((AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteResponse AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService.delete(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public void delete(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList) {
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteRequest inValue = new AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteResponse retVal = ((AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService)(this)).delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteResponse> AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService.deleteAsync(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteResponse> deleteAsync(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList) {
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteRequest inValue = new AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceDeleteRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            return ((AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindResponse AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService.find(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindRequest request) {
            return base.Channel.find(request);
        }
        
        public AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine find(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.QueryCriteria QueryCriteria) {
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindRequest inValue = new AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindResponse retVal = ((AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService)(this)).find(inValue);
            return retVal.STMSODailyLine;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindResponse> AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService.findAsync(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindRequest request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindResponse> findAsync(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.QueryCriteria QueryCriteria) {
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindRequest inValue = new AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            return ((AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateResponse AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService.update(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateRequest request) {
            return base.Channel.update(request);
        }
        
        public void update(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList, AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine) {
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateRequest inValue = new AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            inValue.STMSODailyLine = STMSODailyLine;
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateResponse retVal = ((AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService)(this)).update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateResponse> AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService.updateAsync(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateResponse> updateAsync(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.EntityKey[] EntityKeyList, AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine) {
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateRequest inValue = new AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceUpdateRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            inValue.STMSODailyLine = STMSODailyLine;
            return ((AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateResponse AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService.create(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateRequest request) {
            return base.Channel.create(request);
        }
        
        public AxRetailSOAPI.AxRetailSOLine.EntityKey[] create(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine) {
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateRequest inValue = new AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateRequest();
            inValue.CallContext = CallContext;
            inValue.STMSODailyLine = STMSODailyLine;
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateResponse retVal = ((AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService)(this)).create(inValue);
            return retVal.EntityKeyList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateResponse> AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService.createAsync(AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateRequest request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateResponse> createAsync(AxRetailSOAPI.AxRetailSOLine.CallContext CallContext, AxRetailSOAPI.AxRetailSOLine.AxdSTMSODailyLine STMSODailyLine) {
            AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateRequest inValue = new AxRetailSOAPI.AxRetailSOLine.STMSODailyLineServiceCreateRequest();
            inValue.CallContext = CallContext;
            inValue.STMSODailyLine = STMSODailyLine;
            return ((AxRetailSOAPI.AxRetailSOLine.STMSODailyLineService)(this)).createAsync(inValue);
        }
    }
}
