//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxRetailSOAPI.AxRetailSO {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customDetailXmlField;
        
        private FaultMessageList[] faultMessageListArrayField;
        
        private InfologMessage[] infologMessageListField;
        
        private string stackTraceField;
        
        private int xppExceptionTypeField;
        
        private bool xppExceptionTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CustomDetailXml {
            get {
                return this.customDetailXmlField;
            }
            set {
                this.customDetailXmlField = value;
                this.RaisePropertyChanged("CustomDetailXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public FaultMessageList[] FaultMessageListArray {
            get {
                return this.faultMessageListArrayField;
            }
            set {
                this.faultMessageListArrayField = value;
                this.RaisePropertyChanged("FaultMessageListArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
        public InfologMessage[] InfologMessageList {
            get {
                return this.infologMessageListField;
            }
            set {
                this.infologMessageListField = value;
                this.RaisePropertyChanged("InfologMessageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int XppExceptionType {
            get {
                return this.xppExceptionTypeField;
            }
            set {
                this.xppExceptionTypeField = value;
                this.RaisePropertyChanged("XppExceptionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XppExceptionTypeSpecified {
            get {
                return this.xppExceptionTypeFieldSpecified;
            }
            set {
                this.xppExceptionTypeFieldSpecified = value;
                this.RaisePropertyChanged("XppExceptionTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentField;
        
        private string documentOperationField;
        
        private FaultMessage[] faultMessageArrayField;
        
        private string fieldField;
        
        private string serviceField;
        
        private string serviceOperationField;
        
        private string serviceOperationParameterField;
        
        private string xPathField;
        
        private string xmlLineField;
        
        private string xmlPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DocumentOperation {
            get {
                return this.documentOperationField;
            }
            set {
                this.documentOperationField = value;
                this.RaisePropertyChanged("DocumentOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public FaultMessage[] FaultMessageArray {
            get {
                return this.faultMessageArrayField;
            }
            set {
                this.faultMessageArrayField = value;
                this.RaisePropertyChanged("FaultMessageArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ServiceOperation {
            get {
                return this.serviceOperationField;
            }
            set {
                this.serviceOperationField = value;
                this.RaisePropertyChanged("ServiceOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ServiceOperationParameter {
            get {
                return this.serviceOperationParameterField;
            }
            set {
                this.serviceOperationParameterField = value;
                this.RaisePropertyChanged("ServiceOperationParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
                this.RaisePropertyChanged("XPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string XmlLine {
            get {
                return this.xmlLineField;
            }
            set {
                this.xmlLineField = value;
                this.RaisePropertyChanged("XmlLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string XmlPosition {
            get {
                return this.xmlPositionField;
            }
            set {
                this.xmlPositionField = value;
                this.RaisePropertyChanged("XmlPosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfologMessageType infologMessageTypeField;
        
        private bool infologMessageTypeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfologMessageType InfologMessageType {
            get {
                return this.infologMessageTypeField;
            }
            set {
                this.infologMessageTypeField = value;
                this.RaisePropertyChanged("InfologMessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfologMessageTypeSpecified {
            get {
                return this.infologMessageTypeFieldSpecified;
            }
            set {
                this.infologMessageTypeFieldSpecified = value;
                this.RaisePropertyChanged("InfologMessageTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType {
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class KeyField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyField[] keyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyField[] KeyData {
            get {
                return this.keyDataField;
            }
            set {
                this.keyDataField = value;
                this.RaisePropertyChanged("KeyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="AxRetailSO.SalesDailyService")]
    public interface SalesDailyService {
        
        // CODEGEN: Generating message contract since the wrapper name (SalesDailyServiceDeleteRequest) of message SalesDailyServiceDeleteRequest does not match the default value (delete)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDailyService/delete", ReplyAction="http://tempuri.org/SalesDailyService/deleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSO.AifFault), Action="http://tempuri.org/SalesDailyService/deleteAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteResponse delete(AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDailyService/delete", ReplyAction="http://tempuri.org/SalesDailyService/deleteResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteResponse> deleteAsync(AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SalesDailyServiceUpdateRequest) of message SalesDailyServiceUpdateRequest does not match the default value (update)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDailyService/update", ReplyAction="http://tempuri.org/SalesDailyService/updateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSO.AifFault), Action="http://tempuri.org/SalesDailyService/updateAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateResponse update(AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDailyService/update", ReplyAction="http://tempuri.org/SalesDailyService/updateResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateResponse> updateAsync(AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SalesDailyServiceReadRequest) of message SalesDailyServiceReadRequest does not match the default value (read)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDailyService/read", ReplyAction="http://tempuri.org/SalesDailyService/readResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSO.AifFault), Action="http://tempuri.org/SalesDailyService/readAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadResponse read(AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDailyService/read", ReplyAction="http://tempuri.org/SalesDailyService/readResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadResponse> readAsync(AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SalesDailyServiceCreateRequest) of message SalesDailyServiceCreateRequest does not match the default value (create)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDailyService/create", ReplyAction="http://tempuri.org/SalesDailyService/createResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSO.AifFault), Action="http://tempuri.org/SalesDailyService/createAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateResponse create(AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDailyService/create", ReplyAction="http://tempuri.org/SalesDailyService/createResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateResponse> createAsync(AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SalesDailyServiceFindRequest) of message SalesDailyServiceFindRequest does not match the default value (find)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDailyService/find", ReplyAction="http://tempuri.org/SalesDailyService/findResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AxRetailSOAPI.AxRetailSO.AifFault), Action="http://tempuri.org/SalesDailyService/findAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindResponse find(AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDailyService/find", ReplyAction="http://tempuri.org/SalesDailyService/findResponse")]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindResponse> findAsync(AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyField;
        
        private string languageField;
        
        private string logonAsUserField;
        
        private string messageIdField;
        
        private string partitionKeyField;
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] propertyBagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LogonAsUser {
            get {
                return this.logonAsUserField;
            }
            set {
                this.logonAsUserField = value;
                this.RaisePropertyChanged("LogonAsUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string PartitionKey {
            get {
                return this.partitionKeyField;
            }
            set {
                this.partitionKeyField = value;
                this.RaisePropertyChanged("PartitionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] PropertyBag {
            get {
                return this.propertyBagField;
            }
            set {
                this.propertyBagField = value;
                this.RaisePropertyChanged("PropertyBag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesDailyServiceDeleteRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SalesDailyServiceDeleteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSO.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList;
        
        public SalesDailyServiceDeleteRequest() {
        }
        
        public SalesDailyServiceDeleteRequest(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesDailyServiceDeleteResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SalesDailyServiceDeleteResponse {
        
        public SalesDailyServiceDeleteResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/SalesDaily")]
    public partial class AxdSalesDaily : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<AxdEnum_boolean> clearNilFieldsOnUpdateField;
        
        private bool clearNilFieldsOnUpdateFieldSpecified;
        
        private System.Nullable<AxdEnum_XMLDocPurpose> docPurposeField;
        
        private bool docPurposeFieldSpecified;
        
        private string senderIdField;
        
        private AxdEntity_StmSalesSoDaily[] stmSalesSoDailyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<AxdEnum_boolean> ClearNilFieldsOnUpdate {
            get {
                return this.clearNilFieldsOnUpdateField;
            }
            set {
                this.clearNilFieldsOnUpdateField = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearNilFieldsOnUpdateSpecified {
            get {
                return this.clearNilFieldsOnUpdateFieldSpecified;
            }
            set {
                this.clearNilFieldsOnUpdateFieldSpecified = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<AxdEnum_XMLDocPurpose> DocPurpose {
            get {
                return this.docPurposeField;
            }
            set {
                this.docPurposeField = value;
                this.RaisePropertyChanged("DocPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocPurposeSpecified {
            get {
                return this.docPurposeFieldSpecified;
            }
            set {
                this.docPurposeFieldSpecified = value;
                this.RaisePropertyChanged("DocPurposeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("SenderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StmSalesSoDaily", Order=3)]
        public AxdEntity_StmSalesSoDaily[] StmSalesSoDaily {
            get {
                return this.stmSalesSoDailyField;
            }
            set {
                this.stmSalesSoDailyField = value;
                this.RaisePropertyChanged("StmSalesSoDaily");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_boolean {
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        @true,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_XMLDocPurpose {
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        Duplicate,
        
        /// <remarks/>
        Proforma,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/SalesDaily")]
    public partial class AxdEntity_StmSalesSoDaily : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _DocumentHashField;
        
        private System.Nullable<System.DateTime> confirmDateField;
        
        private bool confirmDateFieldSpecified;
        
        private System.Nullable<System.DateTime> dueDateField;
        
        private bool dueDateFieldSpecified;
        
        private string purchIdField;
        
        private System.Nullable<long> recIdField;
        
        private bool recIdFieldSpecified;
        
        private System.Nullable<int> recVersionField;
        
        private bool recVersionFieldSpecified;
        
        private System.Nullable<decimal> salesAmountField;
        
        private bool salesAmountFieldSpecified;
        
        private System.Nullable<System.DateTime> salesDateField;
        
        private bool salesDateFieldSpecified;
        
        private string salesIdField;
        
        private string salesNameField;
        
        private string salesPoolIdField;
        
        private System.Nullable<decimal> salesQtyField;
        
        private bool salesQtyFieldSpecified;
        
        private string stmStoreIdField;
        
        private string classField;
        
        private AxdEnum_AxdEntityAction actionField;
        
        private bool actionFieldSpecified;
        
        public AxdEntity_StmSalesSoDaily() {
            this.classField = "entity";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string _DocumentHash {
            get {
                return this._DocumentHashField;
            }
            set {
                this._DocumentHashField = value;
                this.RaisePropertyChanged("_DocumentHash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> ConfirmDate {
            get {
                return this.confirmDateField;
            }
            set {
                this.confirmDateField = value;
                this.RaisePropertyChanged("ConfirmDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfirmDateSpecified {
            get {
                return this.confirmDateFieldSpecified;
            }
            set {
                this.confirmDateFieldSpecified = value;
                this.RaisePropertyChanged("ConfirmDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
                this.RaisePropertyChanged("DueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DueDateSpecified {
            get {
                return this.dueDateFieldSpecified;
            }
            set {
                this.dueDateFieldSpecified = value;
                this.RaisePropertyChanged("DueDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string PurchId {
            get {
                return this.purchIdField;
            }
            set {
                this.purchIdField = value;
                this.RaisePropertyChanged("PurchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> RecId {
            get {
                return this.recIdField;
            }
            set {
                this.recIdField = value;
                this.RaisePropertyChanged("RecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecIdSpecified {
            get {
                return this.recIdFieldSpecified;
            }
            set {
                this.recIdFieldSpecified = value;
                this.RaisePropertyChanged("RecIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> RecVersion {
            get {
                return this.recVersionField;
            }
            set {
                this.recVersionField = value;
                this.RaisePropertyChanged("RecVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecVersionSpecified {
            get {
                return this.recVersionFieldSpecified;
            }
            set {
                this.recVersionFieldSpecified = value;
                this.RaisePropertyChanged("RecVersionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> SalesAmount {
            get {
                return this.salesAmountField;
            }
            set {
                this.salesAmountField = value;
                this.RaisePropertyChanged("SalesAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesAmountSpecified {
            get {
                return this.salesAmountFieldSpecified;
            }
            set {
                this.salesAmountFieldSpecified = value;
                this.RaisePropertyChanged("SalesAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> SalesDate {
            get {
                return this.salesDateField;
            }
            set {
                this.salesDateField = value;
                this.RaisePropertyChanged("SalesDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesDateSpecified {
            get {
                return this.salesDateFieldSpecified;
            }
            set {
                this.salesDateFieldSpecified = value;
                this.RaisePropertyChanged("SalesDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string SalesId {
            get {
                return this.salesIdField;
            }
            set {
                this.salesIdField = value;
                this.RaisePropertyChanged("SalesId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string SalesName {
            get {
                return this.salesNameField;
            }
            set {
                this.salesNameField = value;
                this.RaisePropertyChanged("SalesName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string SalesPoolId {
            get {
                return this.salesPoolIdField;
            }
            set {
                this.salesPoolIdField = value;
                this.RaisePropertyChanged("SalesPoolId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> SalesQty {
            get {
                return this.salesQtyField;
            }
            set {
                this.salesQtyField = value;
                this.RaisePropertyChanged("SalesQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesQtySpecified {
            get {
                return this.salesQtyFieldSpecified;
            }
            set {
                this.salesQtyFieldSpecified = value;
                this.RaisePropertyChanged("SalesQtySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string StmStoreId {
            get {
                return this.stmStoreIdField;
            }
            set {
                this.stmStoreIdField = value;
                this.RaisePropertyChanged("StmStoreId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AxdEnum_AxdEntityAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_AxdEntityAction {
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        replace,
        
        /// <remarks/>
        delete,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesDailyServiceUpdateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SalesDailyServiceUpdateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSO.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/SalesDaily", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/SalesDaily")]
        public AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily;
        
        public SalesDailyServiceUpdateRequest() {
        }
        
        public SalesDailyServiceUpdateRequest(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList, AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
            this.SalesDaily = SalesDaily;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesDailyServiceUpdateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SalesDailyServiceUpdateResponse {
        
        public SalesDailyServiceUpdateResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesDailyServiceReadRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SalesDailyServiceReadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSO.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList;
        
        public SalesDailyServiceReadRequest() {
        }
        
        public SalesDailyServiceReadRequest(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesDailyServiceReadResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SalesDailyServiceReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/SalesDaily", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/SalesDaily")]
        public AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily;
        
        public SalesDailyServiceReadResponse() {
        }
        
        public SalesDailyServiceReadResponse(AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily) {
            this.SalesDaily = SalesDaily;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesDailyServiceCreateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SalesDailyServiceCreateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSO.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/SalesDaily", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/SalesDaily")]
        public AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily;
        
        public SalesDailyServiceCreateRequest() {
        }
        
        public SalesDailyServiceCreateRequest(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily) {
            this.CallContext = CallContext;
            this.SalesDaily = SalesDaily;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesDailyServiceCreateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SalesDailyServiceCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList;
        
        public SalesDailyServiceCreateResponse() {
        }
        
        public SalesDailyServiceCreateResponse(AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList) {
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class QueryCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CriteriaElement[] criteriaElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CriteriaElement", Order=0)]
        public CriteriaElement[] CriteriaElement {
            get {
                return this.criteriaElementField;
            }
            set {
                this.criteriaElementField = value;
                this.RaisePropertyChanged("CriteriaElement");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class CriteriaElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataSourceNameField;
        
        private string fieldNameField;
        
        private Operator operatorField;
        
        private string value1Field;
        
        private string value2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                this.dataSourceNameField = value;
                this.RaisePropertyChanged("DataSourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Operator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
                this.RaisePropertyChanged("Value1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
                this.RaisePropertyChanged("Value2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public enum Operator {
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Range,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesDailyServiceFindRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SalesDailyServiceFindRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AxRetailSOAPI.AxRetailSO.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
        public AxRetailSOAPI.AxRetailSO.QueryCriteria QueryCriteria;
        
        public SalesDailyServiceFindRequest() {
        }
        
        public SalesDailyServiceFindRequest(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.QueryCriteria QueryCriteria) {
            this.CallContext = CallContext;
            this.QueryCriteria = QueryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesDailyServiceFindResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SalesDailyServiceFindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/SalesDaily", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/SalesDaily")]
        public AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily;
        
        public SalesDailyServiceFindResponse() {
        }
        
        public SalesDailyServiceFindResponse(AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily) {
            this.SalesDaily = SalesDaily;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalesDailyServiceChannel : AxRetailSOAPI.AxRetailSO.SalesDailyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesDailyServiceClient : System.ServiceModel.ClientBase<AxRetailSOAPI.AxRetailSO.SalesDailyService>, AxRetailSOAPI.AxRetailSO.SalesDailyService {
        
        public SalesDailyServiceClient() {
        }
        
        public SalesDailyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesDailyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesDailyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesDailyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteResponse AxRetailSOAPI.AxRetailSO.SalesDailyService.delete(AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public void delete(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList) {
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteRequest inValue = new AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteResponse retVal = ((AxRetailSOAPI.AxRetailSO.SalesDailyService)(this)).delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteResponse> AxRetailSOAPI.AxRetailSO.SalesDailyService.deleteAsync(AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteResponse> deleteAsync(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList) {
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteRequest inValue = new AxRetailSOAPI.AxRetailSO.SalesDailyServiceDeleteRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            return ((AxRetailSOAPI.AxRetailSO.SalesDailyService)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateResponse AxRetailSOAPI.AxRetailSO.SalesDailyService.update(AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateRequest request) {
            return base.Channel.update(request);
        }
        
        public void update(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList, AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily) {
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateRequest inValue = new AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            inValue.SalesDaily = SalesDaily;
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateResponse retVal = ((AxRetailSOAPI.AxRetailSO.SalesDailyService)(this)).update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateResponse> AxRetailSOAPI.AxRetailSO.SalesDailyService.updateAsync(AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateResponse> updateAsync(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList, AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily) {
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateRequest inValue = new AxRetailSOAPI.AxRetailSO.SalesDailyServiceUpdateRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            inValue.SalesDaily = SalesDaily;
            return ((AxRetailSOAPI.AxRetailSO.SalesDailyService)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadResponse AxRetailSOAPI.AxRetailSO.SalesDailyService.read(AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadRequest request) {
            return base.Channel.read(request);
        }
        
        public AxRetailSOAPI.AxRetailSO.AxdSalesDaily read(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList) {
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadRequest inValue = new AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadResponse retVal = ((AxRetailSOAPI.AxRetailSO.SalesDailyService)(this)).read(inValue);
            return retVal.SalesDaily;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadResponse> AxRetailSOAPI.AxRetailSO.SalesDailyService.readAsync(AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadRequest request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadResponse> readAsync(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.EntityKey[] EntityKeyList) {
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadRequest inValue = new AxRetailSOAPI.AxRetailSO.SalesDailyServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            return ((AxRetailSOAPI.AxRetailSO.SalesDailyService)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateResponse AxRetailSOAPI.AxRetailSO.SalesDailyService.create(AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateRequest request) {
            return base.Channel.create(request);
        }
        
        public AxRetailSOAPI.AxRetailSO.EntityKey[] create(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily) {
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateRequest inValue = new AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateRequest();
            inValue.CallContext = CallContext;
            inValue.SalesDaily = SalesDaily;
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateResponse retVal = ((AxRetailSOAPI.AxRetailSO.SalesDailyService)(this)).create(inValue);
            return retVal.EntityKeyList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateResponse> AxRetailSOAPI.AxRetailSO.SalesDailyService.createAsync(AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateRequest request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateResponse> createAsync(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.AxdSalesDaily SalesDaily) {
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateRequest inValue = new AxRetailSOAPI.AxRetailSO.SalesDailyServiceCreateRequest();
            inValue.CallContext = CallContext;
            inValue.SalesDaily = SalesDaily;
            return ((AxRetailSOAPI.AxRetailSO.SalesDailyService)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindResponse AxRetailSOAPI.AxRetailSO.SalesDailyService.find(AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindRequest request) {
            return base.Channel.find(request);
        }
        
        public AxRetailSOAPI.AxRetailSO.AxdSalesDaily find(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.QueryCriteria QueryCriteria) {
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindRequest inValue = new AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindResponse retVal = ((AxRetailSOAPI.AxRetailSO.SalesDailyService)(this)).find(inValue);
            return retVal.SalesDaily;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindResponse> AxRetailSOAPI.AxRetailSO.SalesDailyService.findAsync(AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindRequest request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindResponse> findAsync(AxRetailSOAPI.AxRetailSO.CallContext CallContext, AxRetailSOAPI.AxRetailSO.QueryCriteria QueryCriteria) {
            AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindRequest inValue = new AxRetailSOAPI.AxRetailSO.SalesDailyServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            return ((AxRetailSOAPI.AxRetailSO.SalesDailyService)(this)).findAsync(inValue);
        }
    }
}
